name: Build IPA (No Mac)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build app (no signing)
        run: |
          xcodebuild -scheme SmartWebView \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/App.xcarchive archive \
          CODE_SIGNING_ALLOWED=NO

      - name: Package IPA
        run: |
          mkdir Payload
          cp -r build/App.xcarchive/Products/Applications/*.app Payload/
          zip -r app.ipa Payload

      - uses: actions/upload-artifact@v3
        with:
          name: ipa
          path: app.ipa
